{% set name = "seispy" %}

{% set version = "1.3.9" %}



package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/python-{{ name }}/python_{{ name }}-{{ version }}.tar.gz
  sha256: f9fa7c915b1aaec0992c48119c6bc4c9d85093da397b796196beb5225b616402


build:
  number: 0
  noarch: python
  entry_points:
    - gen_rayp_lib=seispy.psrayp:gen_rayp_lib
    - prf=seispy.scripts:prf
    - srf=seispy.scripts:srf
    - setpar=seispy.rf:setpar
    - rf2depth=seispy.rf2depth_makedata:rf2depth
    - plotrt=seispy.scripts:plot_rt
    - plotr=seispy.scripts:plot_r
    - download_catalog=seispy.catalog:main
    - ccp_profile=seispy.scripts:ccp_profile
    - pickdepth=seispy.pickdepth.pickdepthui:main
    - hk=seispy.hk:hk
    - pickrf=seispy.pickrf.pickui:main
    - rfani=seispy.scripts:rfani
    - ccp3d=seispy.scripts:ccp3d
    - rfharmo=seispy.scripts:rfharmo
    - get_pierce_points=seispy.scripts:get_pierce_points
    - veltxt2mod=seispy.modcreator:veltxt2mod
    - get_stations=seispy.scripts:get_stations
    - get_events=seispy.scripts:get_events
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python >=3.10
    - matplotlib-base >=3.5.0
    - numpy <2.0.0
    - obspy
    - pandas
    - pyside6
    - scipy
    - scikits-bootstrap
    - pyproj
    - numba

test:
  requires:
    - python >=3.10
  imports:
    - seispy
  commands:
    - prf -h
    - rf2depth -h
    - download_catalog -h
    - ccp3d -h
    - ccp_profile -h
    - rfani -h
    - rfharmo -h
#   requires:


about:
  home: https://pypi.org/project/python-seispy/
  license: GPL-3.0-or-later
  license_file: LICENSE.txt
  summary: Python module of seismology and receiver functions
  doc_url: https://seispy.xumijian.me/
  dev_url: https://github.com/xumi1993/seispy

extra:
  recipe-maintainers:
    - xumi1993
